variables:
  GIT_LFS_VERSION: "2.5.2"

resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    variables:
      TARGET_PLATFORM: ubuntu
      GIT_LFS_CHECKSUM: 624396e8994578ac38c3e5987889be56dba453c378c0675d56cffbc5b8972aa5
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - script: script/build.sh
        name: Build
      - script: script/package.sh
        name: Package
        # TODO: figure out a way to unify these into a single task
      - task: CopyFiles@2
        inputs:
          contents: "output/*.tar.gz"
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
      - task: CopyFiles@2
        inputs:
          contents: "output/*.lzma"
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
      - task: PublishBuildArtifacts@1

  - job: macOS
    pool:
      vmImage: xcode9-macos10.13
    variables:
      TARGET_PLATFORM: macOS
      GIT_LFS_CHECKSUM: eedb80c79f1d3106aa5f1496ddc505e1c1c86c290293d81fb20c5358c615fd74
    steps:
      - bash: script/build.sh
        name: Build
      - bash: script/package.sh
        name: Package
        # TODO: figure out a way to unify these into a single task
      - task: CopyFiles@2
        inputs:
          contents: "output/*.tar.gz"
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
      - task: CopyFiles@2
        inputs:
          contents: "output/*.lzma"
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
      - task: PublishBuildArtifacts@1

  - job: Windows_64bit
    pool:
      vmImage: vs2017-win2016
    variables:
      TARGET_PLATFORM: win32
      WIN_ARCH: 64
      GIT_LFS_CHECKSUM: d5276eb61dea32b3978c2f68c5cf3ad4a45bf70f1a245ddc86b555db7299c7c9
      GIT_FOR_WINDOWS_URL: https://github.com/git-for-windows/git/releases/download/v2.19.1.windows.1/MinGit-2.19.1-64-bit.zip
      GIT_FOR_WINDOWS_CHECKSUM: f89e103a41bda8e12efeaab198a8c20bb4a84804683862da518ee2cb66a5a5b3
    steps:
      - bash: script/build.sh
        name: Build
      - bash: script/package.sh
        name: Package
        # TODO: figure out a way to unify these into a single task
      - task: CopyFiles@2
        inputs:
          contents: "output/*.tar.gz"
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
      - task: CopyFiles@2
        inputs:
          contents: "output/*.lzma"
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
      - task: PublishBuildArtifacts@1

  - job: Windows_32bit
    pool:
      vmImage: vs2017-win2016
    variables:
      TARGET_PLATFORM: win32
      WIN_ARCH: 32
      GIT_LFS_CHECKSUM: 6cf7d4c169a17dd5b326f903708829e7471368b7e1235ab150ce77555f47b213
      GIT_FOR_WINDOWS_URL: https://github.com/git-for-windows/git/releases/download/v2.19.1.windows.1/MinGit-2.19.1-32-bit.zip
      GIT_FOR_WINDOWS_CHECKSUM: 9bde728fe03f66a022b3e41408902ccfceb56a34067db1f35d6509375b9be922
    steps:
      - bash: script/build.sh
        name: Build
      - bash: script/package.sh
        name: Package
        # TODO: figure out a way to unify these into a single task
      - task: CopyFiles@2
        inputs:
          contents: "output/*.tar.gz"
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
      - task: CopyFiles@2
        inputs:
          contents: "output/*.lzma"
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
      - task: PublishBuildArtifacts@1
